name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Cypress in Parallel
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress test with split
        run: |
          SPLIT=5 SPLIT_INDEX=$(( ${{ matrix.container }} - 1 )) npx cypress run 2> /dev/null

      - name: Upload JSON report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-${{ matrix.container }}
          path: reports/html/.jsons/
          if-no-files-found: warn

  merge-report:
    name: Merge and Generate Report
    runs-on: ubuntu-22.04
    needs: run-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download JSON artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - name: Merge mochawesome JSONs and generate HTML report
        run: |
          mkdir -p reports/merged
          npm install -g mochawesome-merge mochawesome-report-generator

          mochawesome-merge reports/html/.jsons/*.json > reports/merged/mochawesome.json
          marge reports/merged/mochawesome.json --reportDir reports/merged --reportFilename final-report.html

        continue-on-error: true
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: final-html-report
          path: |
            reports/merged/final-report.html
            reports/merged/assets/
            reports/merged/mochawesome.json
